### ISSUE TITLE
Can I know if you fixed that Heruko Toolbet issue just as you mentioned at Stackoverflow???

### ISSUE THREAD

**Issue by nicefellow1234** [SammyIsra/fred#4]
Here is the link : http://stackoverflow.com/questions/33908177/installing-heroku-toolbelt-on-windows-10
As I am having the same problem and I have issued 50 Rep bounty on your question..!
Can I ask if you fixed that problem please???

**Comment by SammyIsra** [comment]
Hi! I stopped trying to install the Toolbelt on Windows, so I won't be able to know if it works now :/ What I ended up doing was to work on a Cloud9 Workspace. If I remember correctly, Heroku Toolbelt is already installed, it just needs to be updated.
